---
- name: Ensure fs exists on data device (if provided)
  filesystem:
    fstype: "{{ storage_fs_type }}"
    dev: "{{ storage_device }}"

- name: Ensure mount point exists
  file:
    state: directory
    path: "{{ storage_path }}"

- name: Ensure data direcory is mounted
  mount:
    path: "{{ storage_path }}"
    src: "{{ storage_device }}"
    fstype: "{{ storage_fs_type }}"
    state: mounted

- name: data path
  file:
    path: "{{ storage_path }}/redpanda"
    state: directory
    owner: root
    group: root
    mode: ugo=rwx
- name: set premissions
  file:
    dest: /var/lib/redpanda
    src: "{{ storage_path }}/redpanda"
    state: link
    owner: root
    group: root
    mode: ugo=rwx