- name: debug
  debug:
    msg: "{{ansible_all_ipv4_addresses}}"

- name: Create zookeeper group
  group:
    name: "zookeeper_group"
    state: present
  tags:
    - zookeeper_group

- name: Create zookeeper user
  user:
    name: "zookeeper_user"
    group: "zookeeper_group"
    state: present
    createhome: no
  tags:
    - zookeeper_user

- name: Check if ZooKeeper has already been downloaded and unpacked
  stat:
    path: /etc/zookeeper
  register: zookeeper_dir

- name: Download zookeeper tar
  get_url:
    dest: "/tmp"
    url: "http://archive.apache.org/dist/zookeeper/zookeeper-3.6.0/apache-zookeeper-3.6.0-bin.tar.gz"
  when: not zookeeper_dir.stat.exists

- name: Create ZooKeeper installation dir
  file:
    path: /usr/share/apache-zookeeper
    state: directory
    group: "zookeeper_group"
    owner: "zookeeper_user"
    mode: 0755
  when: not zookeeper_dir.stat.exists

- name: Unpack Apache ZooKeeper
  unarchive:
    src: /tmp/apache-zookeeper-3.6.0-bin.tar.gz
    dest: /usr/share/apache-zookeeper
    copy: no
    extra_opts: [--strip-components=1]
    group: "zookeeper_group"
    owner: "zookeeper_user"
  when: not zookeeper_dir.stat.exists
  tags:
    - zookeeper_unpack

- name: Create symlink to ZooKeeper installation
  file:
    src: /usr/share/apache-zookeeper
    dest: /etc/zookeeper
    state: link
    group: "zookeeper_group"
    owner: "zookeeper_user"
  tags:
    - zookeeper_dirs

- name: Template /etc/default
  template:
    src: default.j2
    dest: "/etc/default/zookeeper"
    group: "zookeeper_group"
    owner: "zookeeper_user"
    mode: 0644
  notify:
    - restart zookeeper
  tags:
    - zookeeper_config

- name: Template ZooKeeper systemd service file
  template:
    src: zookeeper.service.j2
    dest: /usr/lib/systemd/system/zookeeper.service
    group: "zookeeper_group"
    owner: "zookeeper_user"
    mode: 0644
  tags:
    - zookeeper_service

- name: Create directory for snapshot files and myid file
  file:
    path: /var/lib/zookeeper
    state: directory
    group: "zookeeper_group"
    owner: "zookeeper_user"
    mode: 0755
  tags:
    - zookeeper_dirs

- name: Set zookeeper server id
  template:
    src: myid.j2
    dest: /var/lib/zookeeper/myid
  notify: restart zookeeper

- name: Configure zookeeper
  template:
    src: zoo.j2
    dest: /etc/zookeeper/conf/zoo.cfg
  notify: restart zookeeper

- name: Start zookeeper
  service:
    name: zookeeper.service
    state: started

