---

- name: Create S3 bucket
  aws_s3:
    bucket: "{{ s3_bucket }}"
    mode: create
    region: "{{ aws_region }}"
  delegate_to: 127.0.0.1

- name: Build TomEE Client artifact
  command: mvn -DskipTests clean install tomee:build
  args:
    chdir: "{{ tomee_client_sources_dir }}"
    creates: "{{ tomee_client_artifact_path }}"
  delegate_to: 127.0.0.1

- name: Upload keystore to S3
  aws_s3:
    bucket: "{{ s3_bucket }}"
    mode: put
    object: /jars/broker.ks
    src: broker.ks
    region: "{{ aws_region }}"
  delegate_to: 127.0.0.1

- name: Upload artifact to S3
  aws_s3:
    bucket: "{{ s3_bucket }}"
    mode: put
    object: /jars/client.zip
    src: "{{ tomee_client_artifact_path }}"
    region: "{{ aws_region }}"
  delegate_to: 127.0.0.1
  
- name: Install botocore
  become: yes
  pip:
    name: botocore
    extra_args: --ignore-installed

- name: Install boto3
  become: yes
  pip:
    name: boto3
    extra_args: --ignore-installed

- name: Copy deps artifact from S3
  aws_s3:
    bucket: "{{ s3_bucket }}"
    mode: get
    object: "/jars/{{ item }}"
    dest: "/tmp/{{ item }}"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access }}"
    aws_secret_key: "{{ aws_secret }}"
  with_items:
    - "client.zip"
    - "broker.ks"

- name: Prepare start/stop/status script
  template:
    src: client.sh.j2
    dest: /tmp/client.sh
    mode: 0700
