---

- name: Network setup - basic config
  ec2_vpc_net:
    name: "{{ vpc_name }}"
    state: present
    cidr_block: "{{ vpc_cidr_block }}"
    region: "{{ aws_region }}"
  register: vpc_net

- set_fact: vpc_net="{{ vpc_net.vpc.id }}"

- name: Network setup - public subnet
  ec2_vpc_subnet:
    state: present
    az: "{{ aws_zone }}"
    vpc_id: "{{ vpc_net }}"
    cidr: "{{ subnet_cidr }}"
    region: "{{ aws_region }}"
    tags:
      Name: "Net-facing subnet" #we don't need this tag actually, but a bug prevents us from this section being empty
  register: subnet_external

- set_fact: subnet_external="{{ subnet_external.subnet.id }}"

- name: Network setup - Internet Gateway
  ec2_vpc_igw:
    vpc_id: "{{ vpc_net }}"
    state: present
    region: "{{ aws_region }}"
  register: igw
  
- name: Network setup - routing table
  ec2_vpc_route_table:
    vpc_id: "{{ vpc_net }}"
    region: "{{ aws_region }}"
    tags:
      Name: "mqperf"
    subnets:
      - "{{ subnet_external }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"

- name: Network setup - SSH Security Group
  ec2_group:
    name: "ssh_access"
    description: "ssh_access"
    vpc_id: "{{ vpc_net }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: "{{ ssh_port }}"
        to_port: "{{ ssh_port }}"
        cidr_ip: "{{ all_cidr }}"

- name: Network setup - Grafana Security Group
  ec2_group:
    name: "grafana_access"
    description: "grafana_access"
    vpc_id: "{{ vpc_net }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: "{{ grafana_port }}"
        to_port: "{{ grafana_port }}"
        cidr_ip: "{{ all_cidr }}"

- name: Network setup - Prometheus Security Group
  ec2_group:
    name: "prometheus_access"
    description: "prometheus_access"
    vpc_id: "{{ vpc_net }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: "{{ prometheus_port }}"
        to_port: "{{ prometheus_port }}"
        cidr_ip: "{{ all_cidr }}"

- name: Network setup - RabbitMQ Security Group
  ec2_group:
    name: "rabbitmq_access"
    description: "rabbitmq_access"
    vpc_id: "{{ vpc_net }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: "{{ rabbitmq_port }}"
        to_port: "{{ rabbitmq_port }}"
        cidr_ip: "{{ all_cidr }}"

- name: Network setup - RocketMQ Security Group
  ec2_group:
    name: "rocketmq_access"
    description: "rocketmq_access"
    vpc_id: "{{ vpc_net }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: "{{ rocketmq_name_server_port }}"
        to_port: "{{ rocketmq_name_server_port }}"
        cidr_ip: "{{ all_cidr }}"
      - proto: tcp
        from_port: "{{ rocketmq_broker_port_main }}"
        to_port: "{{ rocketmq_broker_port_main }}"
        cidr_ip: "{{ all_cidr }}"

- name: Network setup - ActiveMQ Security Group
  ec2_group:
    name: "activemq_access"
    description: "activemq_access"
    vpc_id: "{{ vpc_net }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: "{{ activemq_port }}"
        to_port: "{{ activemq_port }}"
        cidr_ip: "{{ all_cidr }}"

- name: Network setup - ActiveMQ Artemis Security Group
  ec2_group:
    name: "activemq_artemis_access"
    description: "activemq_artemis_access"
    vpc_id: "{{ vpc_net }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: "{{ activemq_artemis_jolokia_port }}"
        to_port: "{{ activemq_artemis_jolokia_port }}"
        cidr_ip: "{{ all_cidr }}"

- name: Network setup - EventStore Security Group
  ec2_group:
    name: "eventstore_access"
    description: "eventstore_access"
    vpc_id: "{{ vpc_net }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: "{{ eventstore_port }}"
        to_port: "{{ eventstore_port }}"
        cidr_ip: "{{ all_cidr }}"

- name: Network setup - Redpanda Security Group
  ec2_group:
    name: "redpanda_access"
    description: "redpanda_access"
    vpc_id: "{{ vpc_net }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: "{{ redpanda_port }}"
        to_port: "{{ redpanda_port }}"
        cidr_ip: "{{ all_cidr }}"

- name: Network setup - Redistreams Security Group
  ec2_group:
    name: "redistreams_access"
    description: "redistreams_access"
    vpc_id: "{{ vpc_net }}"
    region: "{{ aws_region }}"
    rules:
      - proto: tcp
        from_port: "{{ redistreams_master_port }}"
        to_port: "{{ redistreams_slave2_port }}"
        cidr_ip: "{{ all_cidr }}"

- name: Create an EC2 key
  ec2_key:
    name: "{{ key_name }}"
    region: "{{ aws_region }}"
  register: ec2_key

- name: Save private key
  copy:
    content: "{{ ec2_key.key.private_key }}" 
    dest: "./{{ key_name }}.pem" 
    mode: 0600
  when: ec2_key.changed
