---
aws_region: eu-west-1
aws_zone: "{{ aws_region }}a"
vpc_cidr_block: "172.22.0.0/16"
key_name: "mqperf-key"
vpc_name: "mqperf-vpc"
subnet_cidr: "172.22.1.0/24"

s3_bucket: sml-mqperf-2021

aws_access: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

mqperf_sources_dir: "{{ playbook_dir }}/.."

grafana_port: 3000
prometheus_port: 9090
rabbitmq_port: 15672
activemq_port: 8161
eventstore_port: 2113
activemq_artemis_jolokia_port: 8161
rocketmq_name_server_port: 9876
rocketmq_broker_port_main: 10911

storage_fs_type: ext4
storage_device: /dev/nvme1n1
ec2_instance_type: r5.2xlarge

nats_version: v0.19.0
