---
- name: Install botocore
  become: yes
  pip:
    name: botocore
    extra_args: --ignore-installed

- name: Install boto3
  become: yes
  pip:
    name: boto3
    extra_args: --ignore-installed

- name: Copy ActiveMQ artifact from S3
  aws_s3:
    bucket: "{{ s3_bucket }}"
    mode: get
    object: "/jars/activemq.tar.gz"
    dest: "/tmp/activemq.tar.gz"
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access }}"
    aws_secret_key: "{{ aws_secret }}"

- name: Create activemq user
  user:
    name: "{{ activemq_username }}"
    shell: /bin/bash

- name: Unpack archive
  unarchive:
    copy: no
    dest: /opt
    src: "/tmp/activemq.tar.gz"
    creates: /opt/{{ activemq_name }}
    owner: "{{ activemq_username }}"

- name: Create user friendly link
  file:
    state: link
    src: /opt/{{ activemq_name }}
    dest: /opt/activemq

- name: Create config file
  template:
    src: activemq.xml.j2
    dest: /opt/activemq/conf/activemq.xml

- name: Create env file
  template:
    src: env.j2
    dest: /opt/activemq/bin/env

- name: Configure activemq user
  lineinfile:
    regexp: "ACTIVEMQ_USER"
    line: "ACTIVEMQ_USER=\"{{ activemq_username }}\""
    path: /opt/activemq/bin/env

- name: Link init script to /etc/init.d
  file:
    state: link
    src: /opt/activemq/bin/activemq
    dest: /etc/init.d/activemq

- name: File permissions
  shell: "sudo chmod 600 /opt/activemq/conf/jmx.*"

- name: Start activemq
  shell: "sudo service activemq start"


