---
- hosts: localhost
  connection: local
  gather_facts: False

  environment:
    AWS_REGION: "{{ aws_region }}"
    MAVEN_OPTS: "-Xmx2g"

  tasks:
  - name: Create S3 bucket
    aws_s3:
      bucket: "{{ s3_bucket }}"
      mode: create
      region: "{{ aws_region }}"

  - name: Build ActiveMQ artifact
    command: mvn -DskipTests clean install
    args:
      chdir: "{{ activemq_build_sources_dir }}"
      creates: "{{ activemq_build_artifact_path }}"

  - name: Upload ActiveMQ to S3
    aws_s3:
      bucket: "{{ s3_bucket }}"
      mode: put
      object: /jars/activemq.tar.gz
      src: "{{ activemq_build_artifact_path }}"
      region: "{{ aws_region }}"
