---
- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, count: 3, ec2_groups: [ 'ssh_access', 'default', 'redpanda_access'], aws_instance_type: "{{ ec2_instance_type }}", ec2_tag_group: Redpanda, volume_size: 100 }

- hosts: redpanda
  become: true
  roles:
  - role: java
  - role: redpanda
    tags: ['redpanda']
