---
- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, count: 1, ec2_groups: [ 'ssh_access', 'default', 'activemq_access'], aws_instance_type: t2.xlarge, ec2_tag_group: Activemq }

- hosts: activemq
  become: true
  roles:
    - role: java
    - role: python
    - role: activemq_snapshot

