---
- hosts: 127.0.0.1
  connection: local
  roles:
  - { role: ec2_instance, count: 1, ec2_groups: [ 'ssh_access', 'default' ], aws_instance_type: t2.micro, ec2_tag_group: MySQL, root_volume_size: 100 }

- hosts: mysql
  roles:
    - role: mysql
