---
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Delete existing broker.ks file
    file:
      path: "broker.ks"
      state: absent
  - name: Create keystore
    command: "keytool -genkey -keystore broker.ks -keyalg RSA -keysize 2048 -validity 10000 -alias activemq -dname 'cn=activemq, ou=Engineering, o=Tomitribe, c=US' -storepass activemq -keypass activemq"
  roles:
  - { role: ec2_instance, count: 2, ec2_groups: [ 'ssh_access', 'default', 'activemq_access'], aws_instance_type: t2.xlarge, ec2_tag_group: Activemq }

- hosts: activemq
  become: true
  roles:
    - role: java
    - role: python
    - role: activemq

