- hosts: redistreams
  run_once: true
  tasks:
    - name: Create consumer groups
      shell: /etc/redistreams/src/redis-cli -c -p 6380 XGROUP CREATE stream{{ item }} mygroup 0 MKSTREAM
      with_sequence: start=0 end=100