storage_path: /opt/prometheus
receivers: "{{ groups['receiver'] }}"
senders: "{{ groups['sender'] }}"
prometheus_instance: "{{ groups['prometheus'][0] }}"
prometheus_image_tag: v2.28.0
prometheus_port: 9090
grafana_image_tag: 7.5.9
grafana_admin_password: pass
mqperf_scrape_port: 9193